before_script:
  #- ./do_cmake.sh

build:
  script:
    #- cd build
    #- cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DWITH_CCACHE=ON -BOOST_J=32 -DWITH_MGR_DASHBOARD_FRONTEND=OFF -DWITH_SEASTAR=OFF ..
    #- make -j librbd unittest_librbd all
    #- ./run-make-check.sh -DWITH_CCACHE=ON -DWITH_MGR_DASHBOARD_FRONTEND=OFF -DWITH_SEASTAR=OFF ..
    - CTEST_OPTS="-E tox-mgr -V -R run-rbd-unit" ./run-make-check.sh -j4 -DWITH_CCACHE=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DWITH_MGR_DASHBOARD_FRONTEND=OFF -DWITH_SEASTAR=OFF -DWITH_RBD_RWL=ON  -DWITH_CEPHFS=OFF -DWITH_KRBD=OFF -DWITH_MANPAGE=OFF -DWITH_FUSE=OFF -DWITH_XFS=OFF -DWITH_FILESTORE=OFF -DWITH_LIBCEPHFS=OFF -DWITH_LTTNG=OFF -DWITH_BABELTRACE=OFF
